version: '3'

services:
  mydb:
    build: ./backend/mysql
    container_name: db
    volumes:
      - './backend/mysql/init:/docker-entrypoint-initdb.d'
      - './backend/mysql/data:/var/lib/mysql'
      - './backend/mysql/conf:/etc/mysql/conf.d'
      - "./log/mysql:/var/log/mysql"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
  api:
    build: ./backend/api
    container_name: api
    volumes:
      - './backend/api:/app'
    ports:
      - '5000:5000'
    command: /bin/sh -c "python run.py"
    links:
      - mydb
  app:
    build: ./frontend
    container_name: app
    volumes:
      - './frontend/.:/frontend'
    ports:
      - '1234:8080'
    stdin_open: true
    tty: true
    command: /bin/sh
